### PR TITLE
where().first => find_by()

### PR DESCRIPTION
**Pull request by kalmanh**
I know these are functionally equivalent, but I believe find_by() is slighly preferred :)

### CODE REVIEW

**Comment by marcoow** [comment]
I think this does not work in Rails 3

**Comment by kalmanh** [comment]
Probably true, but Rails 3 is a dinosaur :)

http://stackoverflow.com/questions/27618185/when-does-rails-3-2-reach-end-of-life

**Comment by marcoow** [comment]
For now we're supporting it though. I think many people are still using it. Once Rails 5 is released will probably be a good time to drop support. 



Marco Otte-Witte
marco.otte-witte@simplabs.com
http://simplabs.com

**Comment by kalmanh** [comment]
Fair enough :)

**Pull request closed without merging**
