### PR TITLE
Dry authentication tests

### PR DESCRIPTION
**Pull request by fidalgo**
This fixes the issue:  Authentication related tests have a lot of duplicated code #20

### CODE REVIEW

**Comment by oliverbarnes** [comment]
Thanks for this! I would just move the examples in shared contexts into shared examples instead, so shared contexts take care of setup stuff (variables/helper methods, before/after hooks), and shared examples the tests themselves. A lot clearer and easier to track down where things are happening, this way

**Comment by fidalgo** [comment]
@oliverbarnes I've created a new dir for the shared examples and move the authentication shared examples to it.

**Comment by oliverbarnes** [comment]
great, would you also move `oauth2_shared_contexts.rb` to it? And rename it to something more descriptive of the behavior. Though there's context blocks in it, they're not setup contexts, but rather example scenarios

**Comment by fidalgo** [comment]
@oliverbarnes Sorry for the delay, I've commited it so it should be ready for merge.

**Comment by oliverbarnes** [comment]
No worries, thanks for making the changes. Merging :+1:

**Pull request merged**
